name: rsa
version: 0.0.1
author: Axel Christ <adracus@gmail.com>
description: A library providing a simple to use RSA interface
homepage: https://github.com/Adracus/rsa
dependencies:
  asn1lib:
    git: git://github.com/Adracus/asn1lib.git
  bignum: '>=0.0.6 <0.1.0'
  crypto: '>=0.9.0 <0.10.0'
  rsa_pkcs:
    git: git://github.com/Adracus/rsa_pkcs.git
dev_dependencies:
  unittest: '>=0.11.4 <0.12.0'
